<Project>
  <PropertyGroup>
    <MSBuildProjectExtensionsPath>obj\$(RevitYear)\</MSBuildProjectExtensionsPath>
    <BaseIntermediateOutputPath>obj\$(RevitYear)\</BaseIntermediateOutputPath>
    <IntermediateOutputPath>obj\$(RevitYear)\$(Configuration)\$(TargetFramework)\</IntermediateOutputPath>
  </PropertyGroup>
</Project>
