<Project>
  <PropertyGroup>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <EnableDefaultPageItems>false</EnableDefaultPageItems>
    <NoWarn>$(NoWarn);NU1701</NoWarn>
    <DeployToRevitAddins>false</DeployToRevitAddins>
    <RevitSymbol>REVIT$(RevitYear)</RevitSymbol>
    <DebugEngines>
      {351668CC-8477-4fbf-BFE3-5F1006E4DB1F}
    </DebugEngines>
    <SccProjectName></SccProjectName>
    <SccLocalPath></SccLocalPath>
    <SccAuxPath></SccAuxPath>
    <SccProvider></SccProvider>
    <ExpressionBlendVersion>12.0.51020.0</ExpressionBlendVersion>
    <AssemblyTitle>ExcelExporterImporter</AssemblyTitle>
    <Product>Export-Import Excel</Product>
    <Description>Synchronize data back and forth between Revit and Excel.</Description>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <AssemblyVersion>$(RevitYear).0.0.0</AssemblyVersion>
    <FileVersion>$(RevitYear).0.0.0</FileVersion>
    <PlatformTarget>x64</PlatformTarget>
    <StartupObject />
    <ApplicationIcon>ImportExportExcel-Icon.ico</ApplicationIcon>
    <RootNamespace>ExcelExporterImporter</RootNamespace>
    <RevitDependenciesRoot>$(MSBuildProjectDirectory)\..\dependencies\$(RevitYear)</RevitDependenciesRoot>
    <RevitAddinsPath>%25appdata%25\Autodesk\Revit\Addins\$(RevitYear)</RevitAddinsPath>
  </PropertyGroup>

  <PropertyGroup>
    <ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>
      None
    </ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
    <OutputPath>bin\$(Configuration)\Revit$(RevitYear)\</OutputPath>
    <DefineConstants>TRACE;DEBUG;$(RevitSymbol)</DefineConstants>
    <DebugType>full</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|AnyCPU'">
    <OutputPath>bin\$(Configuration)\Revit$(RevitYear)\</OutputPath>
    <DefineConstants>TRACE;$(RevitSymbol)</DefineConstants>
    <DebugType>pdbonly</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EPPlus" Version="4.5.3.2" />
    <PackageReference Include="EPPlusEnumerable" Version="1.1.0.0" />
    <PackageReference Include="log4net" Version="3.3.0" />
    <PackageReference Include="Ookii.Dialogs" Version="1.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Physical" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.FileSystemGlobbing" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Primitives" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="RevitAPI">
      <HintPath>$(RevitDependenciesRoot)\RevitAPI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="RevitAPIUI">
      <HintPath>$(RevitDependenciesRoot)\RevitAPIUI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="AdWindows">
      <HintPath>$(RevitDependenciesRoot)\AdWindows.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Button.cs" />
    <Compile Remove="Command.cs" />
    <Compile Remove="obj\**\*.cs" />
    <EmbeddedResource Remove="obj\**\*" />
    <None Remove="obj\**\*" />
    <Page Remove="obj\**\*" />
    <Content Remove="Addin.addin" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources.fr.Designer.cs">
      <DependentUpon>Resources.fr.resx</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="Resources.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Settings.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
    <Compile Update="Views\ButtonUserControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Views\ButtonUserControl.Designer.cs">
      <DependentUpon>ButtonUserControl.cs</DependentUpon>
    </Compile>
    <Compile Update="Views\MainWindow.xaml.cs">
      <DependentUpon>MainWindow.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\ProgressWindow.xaml.cs">
      <DependentUpon>ProgressWindow.xaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Include="errors.log">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="Resources\Styles1.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </None>
    <None Include="Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <Page Include="Resources\Styles.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="Views\MainWindow.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Views\ProgressWindow.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\logo.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\logo.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\TooIconNoNewVersionMiniGray.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\ToolIconNewVersionMiniGray.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\ToolIconNoConnectMiniGray.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\ToolIconExitMiniGray.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\ToolIconHelpMiniGray.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\ToolIconSupportMiniGray.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\ToolIconNewVersionMini.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\ToolIconNoConnectMini.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\ToolIconHelpMini.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Content Include="ImportExportExcel-Icon.ico" />
    <Content Include="MaterialAssetsSettings.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <SubType>Designer</SubType>
    </Content>
    <Content Include="ParametersSettings.xml">
      <SubType>Designer</SubType>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\apps.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\bimone.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\button.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Resource Include="Resources\iconapp.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\IconButtonDownload.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\IconButtonExportMini.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\IconBiModeMini.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\IconUniModeMini.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\IconBiModeMiniBlue.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\IconUniModeMiniBlue.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Content Include="Resources\mail.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources.fr.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.fr.Designer.cs</LastGenOutput>
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\ButtonUserControl.resx">
      <DependentUpon>ButtonUserControl.cs</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>

  <Target Name="ValidateRevitDependencies" BeforeTargets="Build">
    <Error
      Condition="!Exists('$(RevitDependenciesRoot)\\RevitAPI.dll')"
      Text="Revit API binaries were not found in '$(RevitDependenciesRoot)'. Expected at least RevitAPI.dll." />
  </Target>

  <PropertyGroup Condition="'$(DeployToRevitAddins)' == 'true'">
    <PostBuildEvent>
      copy "$(MSBuildProjectDirectory)\addin.addin" "$(RevitAddinsPath)\$(MSBuildProjectName).addin"
      xcopy "$(MSBuildProjectDirectory)\$(OutputPath)*" "$(RevitAddinsPath)\ExcelExporterImporter\" /S /E /R /I /F /Y
    </PostBuildEvent>
  </PropertyGroup>
</Project>
