<Project>
  <PropertyGroup>
    <RevitYear>2026</RevitYear>
    <TargetFramework>net8.0-windows</TargetFramework>
  </PropertyGroup>

  <Import Project="ExcelExporterImporter.paths.csproj" />
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />
  <Import Project="ExcelExporterImporter.base.csproj" />
  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />
</Project>
